config/routes.rb
Rails.application.routes.draw do
  resources :discs

  resources :artists

end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/models/disc.rb
class Disc < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:nombre, :sexo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.text_field :sexo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Sexo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.nombre %></td>
        <td><%= artist.sexo %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @artist.nombre %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @artist.sexo %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/discs/edit.html.erb
<h1>Editing Disc</h1>

<%= render 'form' %>

<%= link_to 'Show', @disc %> |
<%= link_to 'Back', discs_path %>

app/views/discs/new.html.erb
<h1>New Disc</h1>

<%= render 'form' %>

<%= link_to 'Back', discs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Discos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>